### ISSUE TITLE
Model.joins(:foo).where{foo.bar_id.eq(6)} not working in 1.0.18

### ISSUE THREAD

**Issue by betelgeuse** [activerecord-hackery/squeel#242]
```
1.9.3p392 :043 > Model.joins(:foo).where{foos.bar_id.eq(6)}.where(laa: 2)
NoMethodError:   Model Load (19.4ms)  SELECT "models".* FROM "models" INNER JOIN "foos" ON "foos"."id" = "models"."foo_id"
undefined method `where' for #<ActiveRecord::QueryMethods::WhereChain:0x007fc2884f47f8>
    from (irb):43
```

I tried all kinds of variations in the where but they all resulted in a similar failure with WhereChain not having the methods to chain.
