### ISSUE TITLE
#where returns WhereChain when block returns an association's sifter (Rails 4)

### ISSUE THREAD

**Issue by odedniv** [activerecord-hackery/squeel#293]
Example to reproduce:

``` ruby
class User < ActiveRecord::Base
  sifter(:anonymous) { email == nil }
end

class Post < ActiveRecord::Base
  belongs_to :user
end
```

This code will fail:

``` ruby
> Post.joins(:user).where{user.sifter(:anonymous)}.to_sql
undefined method `to_sql' for #<ActiveRecord::QueryMethods::WhereChain:0x00000005996c18>
```

But this code won't:

``` ruby
> Post.joins(:user).where{user.sifter(:anonymous) & `1 = 1`}.to_sql
=> "SELECT `posts`.* FROM `posts` INNER JOIN `posts`.`user_id` = `users`.`id` WHERE ((`users`.`email` IS NULL AND 1 = 1))"
```

This won't either:

``` ruby
> User.where{sifter(:anonymous)}.to_sql
=> "SELECT `users`.* FROM `users` WHERE (`users`.`email` IS NULL)"
```

All these pieces of code used to work on Rails 3.2.
Haven't debugged it, if you need more information please let me know.

**Comment by marcusg** [comment]
I have the same problem with Rails 4.1.6 - exactly as @odedniv described it.

**Comment by odedniv** [comment]
Yep, this is actually happens also on 4.2. @marcusg my usual fix is to add `` & `1=1` `` in the end =/

**Comment by marcusg** [comment]
@odedniv Yes, I'll this workaround, thanks!

**Comment by CyborgMaster** [comment]
I'm having the same error on Rails 4.2.  

This code: 
``` ruby
    query.where do
      client.sift(:has_phone_number)
    end
```
Throws:
```
NoMethodError: private method `load' called for #<ActiveRecord::QueryMethods::WhereChain:0x000001111f1c58>`
```

Changing it to:
``` ruby
    query.where do
      client.sift(:has_phone_number) & `1=1`
    end
```
Fixes the problem.  

Horrible hack, but it does work for now.

**Comment by AknEp** [comment]
I met same problem with Rails 4.2.3.
This problem is fixed after upgrading to master (and arel are also upgraded to 6.0.3 from 6.0.0)

**Comment by AknEp** [comment]
@ernie why don't you release latest master?

**Comment by ioquatix** [comment]
I don't know if this is relevant or not but the problem is due to this function here:

https://github.com/rails/rails/pull/21504

**Comment by ioquatix** [comment]
Hey, so that PR was merged which should fix this bug.. For anyone who can't update.. here is a monkey patch:

```
module ActiveRecord::QueryMethods
	def where(opts = :chain, *rest)
		if :chain == opts
			WhereChain.new(spawn)
		elsif opts.blank?
			self
		else
			spawn.where!(opts, *rest)
		end
	end
end
```

**Comment by benjaminoakes** [comment]
I didn't find that the `ActiveRecord::QueryMethods#where` monkey patch fixed this bug in our use case, but `1=1` did.
