### ISSUE TITLE
Update to 1.0.4 breaks counts

### ISSUE THREAD

**Issue by the8472** [activerecord-hackery/squeel#131]
Using rails 3.0.13, ruby 1.8.7

```
class Vacancy
  default_scope where{state ^ 'removed'}
  scope :index_scope, joins{applications.outer}.select{["vacancies.*",count(applications.id).as("application_count")]}.group{vacancies.id}
end
```

calling `Vacancy.index_scope.count` results in

```
NoMethodError: undefined method `to_sym' for #<Arel::Attributes::Attribute:0xe909454>
    from /usr/local/rvm/gems/ree-1.8.7-2012.02@mhmr/gems/activerecord-3.0.13/lib/active_record/relation/calculations.rb:212:in `execute_grouped_calculation'
    from /usr/local/rvm/gems/ree-1.8.7-2012.02@mhmr/gems/activerecord-3.0.13/lib/active_record/relation/calculations.rb:180:in `perform_calculation'
    from /usr/local/rvm/gems/ree-1.8.7-2012.02@mhmr/gems/activerecord-3.0.13/lib/active_record/relation/calculations.rb:152:in `calculate'
    from /usr/local/rvm/gems/ree-1.8.7-2012.02@mhmr/gems/activerecord-3.0.13/lib/active_record/relation/calculations.rb:58:in `count'
    from (irb):2
```

The same query works in squeel 1.0.2. And oddly enough, creating the active relation manually instead of using scopes works too.
